# The configurations that used for the recording, feel free to edit them
version: 2
linters:
  enable:
    - gosec
    - goconst
    - govet
    - asciicheck
    - errcheck
    - staticcheck
  disable-all: true

linters-settings:
  gosec:
    excludes:
      - G104 # Audit errors not being checked

run:
  timeout: 10m
  skip-dirs:
    - vendor

issues:
  exclude-rules:
    - linters:
        - errcheck
      text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*print(f|ln)?|os\\.(Un)?Setenv). is not checked"
    - path: service/collector/app_test.go
      linters:
        - errcheck
        - staticcheck
  max-same-issues: 0
  max-issues-per-linter: 0
