apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  config.yml: |
    server:
      enable:
        debug:
          server: {{ .Values.config.debug }}
      listen:
        address: http://0.0.0.0:{{ .Values.config.listenPort }}
    service:
      collector:
        apps:
          # appTeamMappings can be used when the team annotation is missing in Chart.yaml.
          # Make sure you also add the missing annotation.
          appTeamMappings: | {{ nindent 12 .Values.config.appTeamMappings }}
          defaultTeam: "{{ .Values.config.alertDefaultTeam }}"
          # TODO Remove once old releases are archived https://github.com/giantswarm/giantswarm/issues/20027
          retiredTeams: | {{ nindent 12 .Values.config.retiredTeamsMapping }}
        provider:
          kind: '{{ .Values.provider.kind }}'
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''
