apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  config.yml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      collector:
        apps:
          defaultTeam: "honeybadger"
          retiredTeams: |
            batman: "honeybadger",
            biscuit: "honeybadger",
            celestial: "phoenix",
            firecracker: "phoenix",
            ludacris: "honeybadger",
        provider:
          kind: '{{ .Values.provider.kind }}'
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''
