apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  config.yml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      collector:
        apps:
          # appTeamMappings can be used when the team annotation is missing in Chart.yaml.
          # Make sure you also add the missing annotation.
          appTeamMappings: |
            efk-stack-app: "atlas"
          defaultTeam: "honeybadger"
          # TODO Remove once old releases are archived https://github.com/giantswarm/giantswarm/issues/20027
          retiredTeams: |
            batman: "honeybadger"
            biscuit: "honeybadger"
            celestial: "phoenix"
            firecracker: "phoenix"
            halo: "cabbage"
            ludacris: "honeybadger"
        provider:
          kind: '{{ .Values.provider.kind }}'
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''
