apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
{{- if not (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}
    giantswarm.io/monitoring: "true"
  annotations:
    prometheus.io/scrape: "true"
{{- end }}
spec:
  ports:
  - name: web
    port: 8000
  selector:
    {{- include "labels.selector" . | nindent 4 }}
