apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  endpoints:
    - port: web
      scrapeTimeout: {{ .Values.scrape.timeout }}
      interval: {{ .Values.scrape.interval }}
      honorLabels: true
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
