deployment:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 100m
    memory: 100Mi

image:
  name: "giantswarm/app-exporter"
  tag: "[[ .Version ]]"

registry:
  domain: docker.io

provider:
  kind: aws

pod:
  user:
    id: 1000
  group:
    id: 1000

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

verticalPodAutoscaler:
  enabled: true
