deployment:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 100m
    memory: 100Mi

image:
  name: "giantswarm/app-exporter"
  tag: "[[ .Version ]]"

registry:
  domain: docker.io

provider:
  kind: aws
  region: ""

pod:
  user:
    id: 1000
  group:
    id: 1000

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

config:
  debug: true
  listenPort: 8000
  # a team name to use in 'team:' label if we fail to detect the value automatically
  alertDefaultTeam: noteam
  # string of format '| efk-stack-app: "atlas"'
  appTeamMappings: ""
    # string of format '| batman: "honeybadger"'
  retiredTeamsMapping: ""
