deployment:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 100m
    memory: 100Mi

image:
  name: "giantswarm/app-exporter"
  tag: "[[ .Version ]]"

registry:
  domain: docker.io

provider:
  kind: aws
  region: ""

pod:
  user:
    id: 1000
  group:
    id: 1000

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

config:
  debug: true
  listenPort: 8000
  # a team name to use in 'team:' label if we fail to detect the value automatically
  alertDefaultTeam: noteam
  # string of format '| efk-stack-app: "atlas"'
  appTeamMappings: ""
    # string of format '| batman: "honeybadger"'
  retiredTeamsMapping: ""

# Please note scrape section works only if the cluster app-exporter is
# deployed to supports monitoring.coreos.com/v1 CRs. Otherwise it has no
# influence over the default Prometheus configuration.
serviceMonitor:
  enabled: true
  # -- (duration) Prometheus scrape interval.
  interval: "60s"
  # -- (duration) Prometheus scrape timeout.
  scrapeTimeout: "45s"

# Add seccomp profile to pod security context
podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

# Add seccomp profile to container security context
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

podSecurityStandards:
  enforced: false
